"""
cargar_escenarios.py — Correr UNA SOLA VEZ desde tu PC antes de lanzar Docker.

Inserta los escenarios en la BD. Luego cada contenedor toma uno automáticamente.

Uso:
    python Bioalgoritmo/cargar_escenarios.py

Luego:
    docker compose up --scale worker=3
"""

import sys
import os

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

from ManejoDeDatos.basededatos import iniciar_bd, obtener_sesion, cargar_escenarios

ESCENARIOS = [
    # ── Escenario 1: GA agresivo, learning rates altos ───────────────────────
    {
        "nombre": "GA_lr_alto_poblacion_grande",
        "algoritmo": "GA",
        "seed": 42,
        "poblacion_size": 20,
        "num_generaciones": 10,
        "prob_mutacion": 0.3,
        "prob_cruce": 0.8,
        "search_space_json": {
            "learning_rate":    [1e-3, 5e-3, 1e-2],
            "batch_size":       [16, 32],
            "optimizer":        ["adam", "adamw"],
            "epochs":           [20, 30],
            "dropout_rate":     [0.2, 0.3],
            "dense_units":      [256, 512],
            "filters":          [32, 64],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 2: GA conservador, learning rates bajos ────────────────────
    {
        "nombre": "GA_lr_bajo_dropout_alto",
        "algoritmo": "GA",
        "seed": 7,
        "poblacion_size": 15,
        "num_generaciones": 8,
        "prob_mutacion": 0.1,
        "prob_cruce": 0.9,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3],
            "batch_size":       [32, 64],
            "optimizer":        ["adam", "rmsprop"],
            "epochs":           [10, 20],
            "dropout_rate":     [0.4, 0.5],
            "dense_units":      [128, 256],
            "filters":          [32, 64, 128],
            "use_augmentation": [True, False],
        },
    },
    # ── Escenario 3: PSO estándar ─────────────────────────────────────────────
    {
        "nombre": "PSO_estandar",
        "algoritmo": "PSO",
        "seed": 99,
        "poblacion_size": 20,
        "num_generaciones": 10,
        "w_inercia":    0.5,
        "c1_cognitivo": 1.5,
        "c2_social":    1.5,
        "search_space_json": {
            "learning_rate":    [1e-4, 1e-3, 5e-3],
            "batch_size":       [16, 32, 64],
            "optimizer":        ["adam", "sgd", "rmsprop"],
            "epochs":           [10, 20, 30],
            "dropout_rate":     [0.2, 0.3, 0.5],
            "dense_units":      [128, 256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [True, False],
        },
    },
    # ── Escenario 4: PSO explorador (inercia alta) ────────────────────────────
    {
        "nombre": "PSO_exploracion_alta",
        "algoritmo": "PSO",
        "seed": 13,
        "poblacion_size": 25,
        "num_generaciones": 12,
        "w_inercia":    0.9,
        "c1_cognitivo": 2.0,
        "c2_social":    2.0,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3, 5e-3],
            "batch_size":       [16, 32],
            "optimizer":        ["adam", "adamw", "sgd"],
            "epochs":           [15, 25, 35],
            "dropout_rate":     [0.1, 0.3, 0.5],
            "dense_units":      [128, 256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 5: GA largo — búsqueda profunda con 150 generaciones ────────
    {
        "nombre": "GA_largo_150gen",
        "algoritmo": "GA",
        "seed": 21,
        "poblacion_size": 20,
        "num_generaciones": 150,
        "prob_mutacion": 0.2,
        "prob_cruce": 0.85,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3, 5e-3],
            "batch_size":       [16, 32, 64],
            "optimizer":        ["adam", "adamw", "rmsprop"],
            "epochs":           [20, 30, 40],
            "dropout_rate":     [0.2, 0.3, 0.4],
            "dense_units":      [256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 6: GA muy largo — convergencia con 200 generaciones ─────────
    {
        "nombre": "GA_muy_largo_200gen",
        "algoritmo": "GA",
        "seed": 55,
        "poblacion_size": 15,
        "num_generaciones": 200,
        "prob_mutacion": 0.15,
        "prob_cruce": 0.9,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3],
            "batch_size":       [32, 64],
            "optimizer":        ["adam", "adamw"],
            "epochs":           [25, 35, 50],
            "dropout_rate":     [0.2, 0.3, 0.5],
            "dense_units":      [256, 512, 1024],
            "filters":          [64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 7: GA agresivo largo — mutación alta, 120 generaciones ──────
    {
        "nombre": "GA_mutacion_alta_120gen",
        "algoritmo": "GA",
        "seed": 77,
        "poblacion_size": 30,
        "num_generaciones": 120,
        "prob_mutacion": 0.4,
        "prob_cruce": 0.75,
        "search_space_json": {
            "learning_rate":    [1e-3, 5e-3, 1e-2],
            "batch_size":       [16, 32],
            "optimizer":        ["adam", "sgd", "rmsprop"],
            "epochs":           [15, 20, 30],
            "dropout_rate":     [0.1, 0.3, 0.5],
            "dense_units":      [128, 256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [True, False],
        },
    },
    # ── Escenario 8: PSO largo — 150 generaciones, balance cognitivo/social ───
    {
        "nombre": "PSO_largo_150gen",
        "algoritmo": "PSO",
        "seed": 33,
        "poblacion_size": 20,
        "num_generaciones": 150,
        "w_inercia":    0.6,
        "c1_cognitivo": 1.8,
        "c2_social":    1.8,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3, 5e-3],
            "batch_size":       [16, 32, 64],
            "optimizer":        ["adam", "adamw", "rmsprop"],
            "epochs":           [20, 30, 40],
            "dropout_rate":     [0.2, 0.3, 0.4],
            "dense_units":      [256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 9: PSO muy largo — 200 generaciones, inercia baja ───────────
    {
        "nombre": "PSO_muy_largo_200gen",
        "algoritmo": "PSO",
        "seed": 88,
        "poblacion_size": 25,
        "num_generaciones": 200,
        "w_inercia":    0.4,
        "c1_cognitivo": 2.5,
        "c2_social":    1.5,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3],
            "batch_size":       [32, 64],
            "optimizer":        ["adam", "adamw"],
            "epochs":           [25, 35, 50],
            "dropout_rate":     [0.2, 0.4, 0.5],
            "dense_units":      [256, 512, 1024],
            "filters":          [64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 10: PSO social — 180 gen, componente social dominante ───────
    {
        "nombre": "PSO_social_180gen",
        "algoritmo": "PSO",
        "seed": 66,
        "poblacion_size": 30,
        "num_generaciones": 180,
        "w_inercia":    0.7,
        "c1_cognitivo": 1.0,
        "c2_social":    3.0,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3, 5e-3],
            "batch_size":       [16, 32, 64],
            "optimizer":        ["adam", "sgd", "rmsprop", "adamw"],
            "epochs":           [15, 25, 35, 50],
            "dropout_rate":     [0.1, 0.2, 0.3, 0.5],
            "dense_units":      [128, 256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [True, False],
        },
    },
    # ── Escenario 11: GA — SGD puro, 130 generaciones ─────────────────────────
    {
        "nombre": "GA_sgd_130gen",
        "algoritmo": "GA",
        "seed": 101,
        "poblacion_size": 20,
        "num_generaciones": 130,
        "prob_mutacion": 0.25,
        "prob_cruce": 0.8,
        "search_space_json": {
            "learning_rate":    [1e-3, 5e-3, 1e-2],
            "batch_size":       [32, 64],
            "optimizer":        ["sgd"],
            "epochs":           [20, 30, 40],
            "dropout_rate":     [0.2, 0.4],
            "dense_units":      [256, 512],
            "filters":          [64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 12: GA — dropout bajo, filtros grandes, 110 gen ─────────────
    {
        "nombre": "GA_dropout_bajo_110gen",
        "algoritmo": "GA",
        "seed": 202,
        "poblacion_size": 15,
        "num_generaciones": 110,
        "prob_mutacion": 0.1,
        "prob_cruce": 0.95,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3],
            "batch_size":       [16, 32],
            "optimizer":        ["adam", "adamw"],
            "epochs":           [30, 40, 50],
            "dropout_rate":     [0.05, 0.1, 0.2],
            "dense_units":      [512, 1024],
            "filters":          [128, 256],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 13: GA — sin augmentation, 160 gen ──────────────────────────
    {
        "nombre": "GA_sin_augmentation_160gen",
        "algoritmo": "GA",
        "seed": 303,
        "poblacion_size": 20,
        "num_generaciones": 160,
        "prob_mutacion": 0.2,
        "prob_cruce": 0.8,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3],
            "batch_size":       [32, 64],
            "optimizer":        ["adam", "rmsprop"],
            "epochs":           [25, 35],
            "dropout_rate":     [0.3, 0.4, 0.5],
            "dense_units":      [128, 256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [False],
        },
    },
    # ── Escenario 14: GA — batch grande, epochs largo, 140 gen ────────────────
    {
        "nombre": "GA_batch_grande_140gen",
        "algoritmo": "GA",
        "seed": 404,
        "poblacion_size": 20,
        "num_generaciones": 140,
        "prob_mutacion": 0.3,
        "prob_cruce": 0.7,
        "search_space_json": {
            "learning_rate":    [5e-4, 1e-3, 5e-3],
            "batch_size":       [64, 128],
            "optimizer":        ["adam", "adamw", "sgd"],
            "epochs":           [40, 50, 60],
            "dropout_rate":     [0.2, 0.3],
            "dense_units":      [256, 512],
            "filters":          [64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 15: GA — población pequeña, 170 gen ─────────────────────────
    {
        "nombre": "GA_poblacion_pequena_170gen",
        "algoritmo": "GA",
        "seed": 505,
        "poblacion_size": 10,
        "num_generaciones": 170,
        "prob_mutacion": 0.2,
        "prob_cruce": 0.85,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3, 5e-3],
            "batch_size":       [16, 32, 64],
            "optimizer":        ["adam", "adamw", "rmsprop"],
            "epochs":           [20, 30, 40],
            "dropout_rate":     [0.2, 0.3, 0.4, 0.5],
            "dense_units":      [128, 256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [True, False],
        },
    },
    # ── Escenario 16: GA — población grande, 190 gen ──────────────────────────
    {
        "nombre": "GA_poblacion_grande_190gen",
        "algoritmo": "GA",
        "seed": 606,
        "poblacion_size": 40,
        "num_generaciones": 190,
        "prob_mutacion": 0.2,
        "prob_cruce": 0.8,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3],
            "batch_size":       [32, 64],
            "optimizer":        ["adam", "adamw"],
            "epochs":           [25, 35],
            "dropout_rate":     [0.2, 0.3, 0.4],
            "dense_units":      [256, 512],
            "filters":          [64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 17: GA — mutación muy alta, 115 gen ─────────────────────────
    {
        "nombre": "GA_mutacion_muy_alta_115gen",
        "algoritmo": "GA",
        "seed": 707,
        "poblacion_size": 25,
        "num_generaciones": 115,
        "prob_mutacion": 0.5,
        "prob_cruce": 0.6,
        "search_space_json": {
            "learning_rate":    [1e-3, 5e-3, 1e-2],
            "batch_size":       [16, 32],
            "optimizer":        ["adam", "sgd", "rmsprop", "adamw"],
            "epochs":           [15, 20, 30],
            "dropout_rate":     [0.1, 0.3, 0.5],
            "dense_units":      [128, 256, 512, 1024],
            "filters":          [32, 64, 128],
            "use_augmentation": [True, False],
        },
    },
    # ── Escenario 18: GA — lr muy bajo, epochs largo, 125 gen ─────────────────
    {
        "nombre": "GA_lr_muy_bajo_125gen",
        "algoritmo": "GA",
        "seed": 808,
        "poblacion_size": 20,
        "num_generaciones": 125,
        "prob_mutacion": 0.15,
        "prob_cruce": 0.9,
        "search_space_json": {
            "learning_rate":    [1e-5, 5e-5, 1e-4],
            "batch_size":       [32, 64],
            "optimizer":        ["adam", "adamw"],
            "epochs":           [40, 50, 60, 80],
            "dropout_rate":     [0.3, 0.4, 0.5],
            "dense_units":      [256, 512],
            "filters":          [64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 19: GA — rmsprop exclusivo, 135 gen ─────────────────────────
    {
        "nombre": "GA_rmsprop_135gen",
        "algoritmo": "GA",
        "seed": 909,
        "poblacion_size": 20,
        "num_generaciones": 135,
        "prob_mutacion": 0.2,
        "prob_cruce": 0.85,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3, 5e-3],
            "batch_size":       [16, 32, 64],
            "optimizer":        ["rmsprop"],
            "epochs":           [20, 30, 40],
            "dropout_rate":     [0.2, 0.3, 0.4],
            "dense_units":      [256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 20: GA — espacio amplio, 155 gen ────────────────────────────
    {
        "nombre": "GA_espacio_amplio_155gen",
        "algoritmo": "GA",
        "seed": 1010,
        "poblacion_size": 25,
        "num_generaciones": 155,
        "prob_mutacion": 0.25,
        "prob_cruce": 0.8,
        "search_space_json": {
            "learning_rate":    [1e-5, 1e-4, 5e-4, 1e-3, 5e-3],
            "batch_size":       [16, 32, 64, 128],
            "optimizer":        ["adam", "adamw", "sgd", "rmsprop"],
            "epochs":           [15, 20, 30, 40, 50],
            "dropout_rate":     [0.1, 0.2, 0.3, 0.4, 0.5],
            "dense_units":      [128, 256, 512, 1024],
            "filters":          [32, 64, 128],
            "use_augmentation": [True, False],
        },
    },
    # ── Escenario 21: PSO — cognitivo dominante, 130 gen ──────────────────────
    {
        "nombre": "PSO_cognitivo_130gen",
        "algoritmo": "PSO",
        "seed": 111,
        "poblacion_size": 20,
        "num_generaciones": 130,
        "w_inercia":    0.5,
        "c1_cognitivo": 3.0,
        "c2_social":    1.0,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3, 5e-3],
            "batch_size":       [16, 32, 64],
            "optimizer":        ["adam", "adamw", "rmsprop"],
            "epochs":           [20, 30, 40],
            "dropout_rate":     [0.2, 0.3, 0.4],
            "dense_units":      [256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 22: PSO — inercia media, 110 gen ────────────────────────────
    {
        "nombre": "PSO_inercia_media_110gen",
        "algoritmo": "PSO",
        "seed": 222,
        "poblacion_size": 15,
        "num_generaciones": 110,
        "w_inercia":    0.6,
        "c1_cognitivo": 2.0,
        "c2_social":    2.0,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3],
            "batch_size":       [32, 64],
            "optimizer":        ["adam", "adamw"],
            "epochs":           [25, 35, 50],
            "dropout_rate":     [0.2, 0.3, 0.5],
            "dense_units":      [256, 512, 1024],
            "filters":          [64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 23: PSO — inercia baja (explotación), 160 gen ──────────────
    {
        "nombre": "PSO_explotacion_160gen",
        "algoritmo": "PSO",
        "seed": 333,
        "poblacion_size": 20,
        "num_generaciones": 160,
        "w_inercia":    0.3,
        "c1_cognitivo": 2.0,
        "c2_social":    2.0,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3],
            "batch_size":       [32, 64],
            "optimizer":        ["adam", "adamw"],
            "epochs":           [30, 40],
            "dropout_rate":     [0.2, 0.3, 0.4],
            "dense_units":      [256, 512],
            "filters":          [64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 24: PSO — sin augmentation, 140 gen ─────────────────────────
    {
        "nombre": "PSO_sin_augmentation_140gen",
        "algoritmo": "PSO",
        "seed": 444,
        "poblacion_size": 20,
        "num_generaciones": 140,
        "w_inercia":    0.6,
        "c1_cognitivo": 1.5,
        "c2_social":    1.5,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3],
            "batch_size":       [32, 64],
            "optimizer":        ["adam", "rmsprop"],
            "epochs":           [25, 35],
            "dropout_rate":     [0.3, 0.4, 0.5],
            "dense_units":      [128, 256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [False],
        },
    },
    # ── Escenario 25: PSO — SGD exclusivo, 120 gen ────────────────────────────
    {
        "nombre": "PSO_sgd_120gen",
        "algoritmo": "PSO",
        "seed": 555,
        "poblacion_size": 20,
        "num_generaciones": 120,
        "w_inercia":    0.7,
        "c1_cognitivo": 1.5,
        "c2_social":    2.5,
        "search_space_json": {
            "learning_rate":    [1e-3, 5e-3, 1e-2],
            "batch_size":       [32, 64],
            "optimizer":        ["sgd"],
            "epochs":           [30, 40, 50],
            "dropout_rate":     [0.2, 0.3, 0.4],
            "dense_units":      [256, 512],
            "filters":          [64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 26: PSO — población pequeña, 170 gen ────────────────────────
    {
        "nombre": "PSO_poblacion_pequena_170gen",
        "algoritmo": "PSO",
        "seed": 666,
        "poblacion_size": 10,
        "num_generaciones": 170,
        "w_inercia":    0.8,
        "c1_cognitivo": 2.0,
        "c2_social":    2.0,
        "search_space_json": {
            "learning_rate":    [1e-4, 5e-4, 1e-3, 5e-3],
            "batch_size":       [16, 32, 64],
            "optimizer":        ["adam", "adamw", "rmsprop"],
            "epochs":           [20, 30, 40],
            "dropout_rate":     [0.2, 0.3, 0.4, 0.5],
            "dense_units":      [128, 256, 512],
            "filters":          [32, 64, 128],
            "use_augmentation": [True, False],
        },
    },
    # ── Escenario 27: PSO — batch pequeño, lr alto, 145 gen ───────────────────
    {
        "nombre": "PSO_batch_pequeno_145gen",
        "algoritmo": "PSO",
        "seed": 777,
        "poblacion_size": 25,
        "num_generaciones": 145,
        "w_inercia":    0.5,
        "c1_cognitivo": 2.5,
        "c2_social":    2.5,
        "search_space_json": {
            "learning_rate":    [1e-3, 5e-3, 1e-2],
            "batch_size":       [8, 16],
            "optimizer":        ["adam", "adamw", "sgd"],
            "epochs":           [15, 20, 25],
            "dropout_rate":     [0.1, 0.2, 0.3],
            "dense_units":      [128, 256, 512],
            "filters":          [32, 64],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 28: PSO — espacio amplio, 165 gen ───────────────────────────
    {
        "nombre": "PSO_espacio_amplio_165gen",
        "algoritmo": "PSO",
        "seed": 888,
        "poblacion_size": 30,
        "num_generaciones": 165,
        "w_inercia":    0.6,
        "c1_cognitivo": 1.8,
        "c2_social":    2.2,
        "search_space_json": {
            "learning_rate":    [1e-5, 1e-4, 5e-4, 1e-3, 5e-3],
            "batch_size":       [16, 32, 64, 128],
            "optimizer":        ["adam", "adamw", "sgd", "rmsprop"],
            "epochs":           [15, 25, 35, 50],
            "dropout_rate":     [0.1, 0.2, 0.3, 0.4, 0.5],
            "dense_units":      [128, 256, 512, 1024],
            "filters":          [32, 64, 128],
            "use_augmentation": [True, False],
        },
    },
    # ── Escenario 29: PSO — lr muy bajo, epochs largo, 185 gen ───────────────
    {
        "nombre": "PSO_lr_muy_bajo_185gen",
        "algoritmo": "PSO",
        "seed": 999,
        "poblacion_size": 20,
        "num_generaciones": 185,
        "w_inercia":    0.5,
        "c1_cognitivo": 2.0,
        "c2_social":    2.0,
        "search_space_json": {
            "learning_rate":    [1e-5, 5e-5, 1e-4],
            "batch_size":       [32, 64],
            "optimizer":        ["adam", "adamw"],
            "epochs":           [50, 60, 80, 100],
            "dropout_rate":     [0.3, 0.4, 0.5],
            "dense_units":      [256, 512],
            "filters":          [64, 128],
            "use_augmentation": [True],
        },
    },
    # ── Escenario 30: PSO — máxima exploración, 195 gen ──────────────────────
    {
        "nombre": "PSO_maxima_exploracion_195gen",
        "algoritmo": "PSO",
        "seed": 2024,
        "poblacion_size": 35,
        "num_generaciones": 195,
        "w_inercia":    0.95,
        "c1_cognitivo": 2.5,
        "c2_social":    2.5,
        "search_space_json": {
            "learning_rate":    [1e-5, 1e-4, 5e-4, 1e-3, 5e-3, 1e-2],
            "batch_size":       [8, 16, 32, 64, 128],
            "optimizer":        ["adam", "adamw", "sgd", "rmsprop"],
            "epochs":           [10, 20, 30, 40, 50, 60],
            "dropout_rate":     [0.05, 0.1, 0.2, 0.3, 0.4, 0.5],
            "dense_units":      [64, 128, 256, 512, 1024],
            "filters":          [16, 32, 64, 128, 256],
            "use_augmentation": [True, False],
        },
    },
]


if __name__ == "__main__":
    print("Inicializando tablas...")
    iniciar_bd()

    sesion = obtener_sesion()
    cargar_escenarios(sesion, ESCENARIOS)
    sesion.close()

    print(f"{len(ESCENARIOS)} escenarios cargados.")
    print("Ahora lanza los contenedores: docker compose up --scale worker=30")
