services:
  worker:
    build: .
    restart: on-failure
    environment:
      base_datos: ${base_datos}
      TF_CPP_MIN_LOG_LEVEL: "3"
      TF_ENABLE_ONEDNN_OPTS: "0"
    mem_limit: 4000m
    deploy:
      replicas: 7
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
        limits:
          memory: 4000M
