services:
  worker:
    build: .
    restart: on-failure
    devices:
      - /dev/kfd
      - /dev/dri
    group_add:
      - video
      - render
    environment:
      base_datos: ${base_datos}
      GPU: ${GPU:-1}
      TF_CPP_MIN_LOG_LEVEL: "3"
      TF_ENABLE_ONEDNN_OPTS: "0"
      HSA_OVERRIDE_GFX_VERSION: "11.0.0"
    mem_limit: 8000m
    deploy:
      replicas: 7
      resources:
        limits:
          memory: 8000M
