services:
  worker:
    build: .
    environment:
      base_datos: postgresql://bioeslaley123:hfgq1cqgqnlvmme0@192.168.15.49:5489/bioeslaonda
      GPU: "0"
      TF_CPP_MIN_LOG_LEVEL: "3"
      TF_ENABLE_ONEDNN_OPTS: "0"
    mem_limit: 8000m
